# Run this script to generate your Striver SDE 30-Day Timetable Excel file.
# Requirements: pip install openpyxl
# Usage: python generate_timetable.py

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.hyperlink import Hyperlink
from datetime import date, timedelta

START_DATE = date(2026, 6, 10)

plan = [
    (1,"Arrays","Arrays Basics","3-4 hrs","Set Matrix Zeroes","https://leetcode.com/problems/set-matrix-zeroes/","Medium"),
    (1,"Arrays","Arrays Basics","3-4 hrs","Pascal's Triangle","https://leetcode.com/problems/pascals-triangle/","Easy"),
    (1,"Arrays","Arrays Basics","3-4 hrs","Next Permutation","https://leetcode.com/problems/next-permutation/","Medium"),
    (1,"Arrays","Arrays Basics","3-4 hrs","Maximum Subarray (Kadane's)","https://leetcode.com/problems/maximum-subarray/","Medium"),
    (1,"Arrays","Arrays Basics","3-4 hrs","Sort Colors (Dutch National Flag)","https://leetcode.com/problems/sort-colors/","Medium"),
    (1,"Arrays","Arrays Basics","3-4 hrs","Best Time to Buy and Sell Stock","https://leetcode.com/problems/best-time-to-buy-and-sell-stock/","Easy"),
    (2,"Arrays","Arrays & Two Pointers","3-4 hrs","Merge Intervals","https://leetcode.com/problems/merge-intervals/","Medium"),
    (2,"Arrays","Arrays & Two Pointers","3-4 hrs","Insert Interval","https://leetcode.com/problems/insert-interval/","Medium"),
    (2,"Arrays","Arrays & Two Pointers","3-4 hrs","3Sum","https://leetcode.com/problems/3sum/","Medium"),
    (2,"Arrays","Arrays & Two Pointers","3-4 hrs","4Sum","https://leetcode.com/problems/4sum/","Medium"),
    (2,"Arrays","Arrays & Two Pointers","3-4 hrs","Longest Substring Without Repeating Characters","https://leetcode.com/problems/longest-substring-without-repeating-characters/","Medium"),
    (2,"Arrays","Arrays & Two Pointers","3-4 hrs","Container With Most Water","https://leetcode.com/problems/container-with-most-water/","Medium"),
    (3,"Arrays","Arrays + Hashing","3-4 hrs","Two Sum","https://leetcode.com/problems/two-sum/","Easy"),
    (3,"Arrays","Arrays + Hashing","3-4 hrs","Subarray Sum Equals K","https://leetcode.com/problems/subarray-sum-equals-k/","Medium"),
    (3,"Arrays","Arrays + Hashing","3-4 hrs","Longest Consecutive Sequence","https://leetcode.com/problems/longest-consecutive-sequence/","Medium"),
    (3,"Arrays","Arrays + Hashing","3-4 hrs","Majority Element","https://leetcode.com/problems/majority-element/","Easy"),
    (3,"Arrays","Arrays + Hashing","3-4 hrs","Majority Element II","https://leetcode.com/problems/majority-element-ii/","Medium"),
    (3,"Arrays","Arrays + Hashing","3-4 hrs","Product of Array Except Self","https://leetcode.com/problems/product-of-array-except-self/","Medium"),
    (4,"Arrays","Searching & Rotations","3-4 hrs","Search in Rotated Sorted Array","https://leetcode.com/problems/search-in-rotated-sorted-array/","Medium"),
    (4,"Arrays","Searching & Rotations","3-4 hrs","Find Minimum in Rotated Sorted Array","https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/","Medium"),
    (4,"Arrays","Searching & Rotations","3-4 hrs","Median of Two Sorted Arrays","https://leetcode.com/problems/median-of-two-sorted-arrays/","Hard"),
    (4,"Arrays","Searching & Rotations","3-4 hrs","Kth Largest Element in an Array","https://leetcode.com/problems/kth-largest-element-in-an-array/","Medium"),
    (4,"Arrays","Searching & Rotations","3-4 hrs","Find the Duplicate Number","https://leetcode.com/problems/find-the-duplicate-number/","Medium"),
    (4,"Arrays","Searching & Rotations","3-4 hrs","Missing Number","https://leetcode.com/problems/missing-number/","Easy"),
    (5,"Arrays","Matrix","3-4 hrs","Rotate Image","https://leetcode.com/problems/rotate-image/","Medium"),
    (5,"Arrays","Matrix","3-4 hrs","Spiral Matrix","https://leetcode.com/problems/spiral-matrix/","Medium"),
    (5,"Arrays","Matrix","3-4 hrs","Search a 2D Matrix","https://leetcode.com/problems/search-a-2d-matrix/","Medium"),
    (5,"Arrays","Matrix","3-4 hrs","Word Search","https://leetcode.com/problems/word-search/","Medium"),
    (5,"Arrays","Matrix","3-4 hrs","Number of Islands","https://leetcode.com/problems/number-of-islands/","Medium"),
    (5,"Arrays","Matrix","3-4 hrs","Maximal Rectangle","https://leetcode.com/problems/maximal-rectangle/","Hard"),
    (6,"Linked List","Linked List Basics","3-4 hrs","Reverse Linked List","https://leetcode.com/problems/reverse-linked-list/","Easy"),
    (6,"Linked List","Linked List Basics","3-4 hrs","Middle of the Linked List","https://leetcode.com/problems/middle-of-the-linked-list/","Easy"),
    (6,"Linked List","Linked List Basics","3-4 hrs","Merge Two Sorted Lists","https://leetcode.com/problems/merge-two-sorted-lists/","Easy"),
    (6,"Linked List","Linked List Basics","3-4 hrs","Remove Nth Node From End of List","https://leetcode.com/problems/remove-nth-node-from-end-of-list/","Medium"),
    (6,"Linked List","Linked List Basics","3-4 hrs","Linked List Cycle","https://leetcode.com/problems/linked-list-cycle/","Easy"),
    (6,"Linked List","Linked List Basics","3-4 hrs","Linked List Cycle II","https://leetcode.com/problems/linked-list-cycle-ii/","Medium"),
    (7,"Linked List","Linked List II","3-4 hrs","Palindrome Linked List","https://leetcode.com/problems/palindrome-linked-list/","Easy"),
    (7,"Linked List","Linked List II","3-4 hrs","Sort List","https://leetcode.com/problems/sort-list/","Medium"),
    (7,"Linked List","Linked List II","3-4 hrs","Reorder List","https://leetcode.com/problems/reorder-list/","Medium"),
    (7,"Linked List","Linked List II","3-4 hrs","Intersection of Two Linked Lists","https://leetcode.com/problems/intersection-of-two-linked-lists/","Easy"),
    (7,"Linked List","Linked List II","3-4 hrs","Add Two Numbers","https://leetcode.com/problems/add-two-numbers/","Medium"),
    (7,"Linked List","Linked List II","3-4 hrs","Rotate List","https://leetcode.com/problems/rotate-list/","Medium"),
    (8,"Linked List","Linked List Advanced","~4 hrs","Copy List with Random Pointer","https://leetcode.com/problems/copy-list-with-random-pointer/","Medium"),
    (8,"Linked List","Linked List Advanced","~4 hrs","Flatten a Multilevel Doubly Linked List","https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/","Medium"),
    (8,"Linked List","Linked List Advanced","~4 hrs","Reverse Nodes in k-Group","https://leetcode.com/problems/reverse-nodes-in-k-group/","Hard"),
    (8,"Linked List","Linked List Advanced","~4 hrs","LRU Cache","https://leetcode.com/problems/lru-cache/","Medium"),
    (8,"Linked List","Linked List Advanced","~4 hrs","LFU Cache","https://leetcode.com/problems/lfu-cache/","Hard"),
    (8,"Linked List","Linked List Advanced","~4 hrs","Odd Even Linked List","https://leetcode.com/problems/odd-even-linked-list/","Medium"),
    (9,"Stack & Queue","Stack","3-4 hrs","Valid Parentheses","https://leetcode.com/problems/valid-parentheses/","Easy"),
    (9,"Stack & Queue","Stack","3-4 hrs","Min Stack","https://leetcode.com/problems/min-stack/","Medium"),
    (9,"Stack & Queue","Stack","3-4 hrs","Largest Rectangle in Histogram","https://leetcode.com/problems/largest-rectangle-in-histogram/","Hard"),
    (9,"Stack & Queue","Stack","3-4 hrs","Evaluate Reverse Polish Notation","https://leetcode.com/problems/evaluate-reverse-polish-notation/","Medium"),
    (9,"Stack & Queue","Stack","3-4 hrs","Daily Temperatures","https://leetcode.com/problems/daily-temperatures/","Medium"),
    (9,"Stack & Queue","Stack","3-4 hrs","Car Fleet","https://leetcode.com/problems/car-fleet/","Medium"),
    (10,"Stack & Queue","Queue & Deque","3-4 hrs","Sliding Window Maximum","https://leetcode.com/problems/sliding-window-maximum/","Hard"),
    (10,"Stack & Queue","Queue & Deque","3-4 hrs","Implement Queue using Stacks","https://leetcode.com/problems/implement-queue-using-stacks/","Easy"),
    (10,"Stack & Queue","Queue & Deque","3-4 hrs","Implement Stack using Queues","https://leetcode.com/problems/implement-stack-using-queues/","Easy"),
    (10,"Stack & Queue","Queue & Deque","3-4 hrs","Design Circular Queue","https://leetcode.com/problems/design-circular-queue/","Medium"),
    (10,"Stack & Queue","Queue & Deque","3-4 hrs","Rotting Oranges","https://leetcode.com/problems/rotting-oranges/","Medium"),
    (10,"Stack & Queue","Queue & Deque","3-4 hrs","Online Stock Span","https://leetcode.com/problems/online-stock-span/","Medium"),
    (11,"Heap","Heap / Priority Queue","~4 hrs","Kth Largest Element in a Stream","https://leetcode.com/problems/kth-largest-element-in-a-stream/","Easy"),
    (11,"Heap","Heap / Priority Queue","~4 hrs","Find Median from Data Stream","https://leetcode.com/problems/find-median-from-data-stream/","Hard"),
    (11,"Heap","Heap / Priority Queue","~4 hrs","Top K Frequent Elements","https://leetcode.com/problems/top-k-frequent-elements/","Medium"),
    (11,"Heap","Heap / Priority Queue","~4 hrs","Merge K Sorted Lists","https://leetcode.com/problems/merge-k-sorted-lists/","Hard"),
    (11,"Heap","Heap / Priority Queue","~4 hrs","Task Scheduler","https://leetcode.com/problems/task-scheduler/","Medium"),
    (11,"Heap","Heap / Priority Queue","~4 hrs","Reorganize String","https://leetcode.com/problems/reorganize-string/","Medium"),
    (12,"Binary Tree","Binary Tree Traversal","3-4 hrs","Binary Tree Inorder Traversal","https://leetcode.com/problems/binary-tree-inorder-traversal/","Easy"),
    (12,"Binary Tree","Binary Tree Traversal","3-4 hrs","Binary Tree Preorder Traversal","https://leetcode.com/problems/binary-tree-preorder-traversal/","Easy"),
    (12,"Binary Tree","Binary Tree Traversal","3-4 hrs","Binary Tree Postorder Traversal","https://leetcode.com/problems/binary-tree-postorder-traversal/","Easy"),
    (12,"Binary Tree","Binary Tree Traversal","3-4 hrs","Binary Tree Level Order Traversal","https://leetcode.com/problems/binary-tree-level-order-traversal/","Medium"),
    (12,"Binary Tree","Binary Tree Traversal","3-4 hrs","Binary Tree Zigzag Level Order Traversal","https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/","Medium"),
    (12,"Binary Tree","Binary Tree Traversal","3-4 hrs","Binary Tree Right Side View","https://leetcode.com/problems/binary-tree-right-side-view/","Medium"),
    (13,"Binary Tree","Binary Tree Properties","3-4 hrs","Maximum Depth of Binary Tree","https://leetcode.com/problems/maximum-depth-of-binary-tree/","Easy"),
    (13,"Binary Tree","Binary Tree Properties","3-4 hrs","Diameter of Binary Tree","https://leetcode.com/problems/diameter-of-binary-tree/","Easy"),
    (13,"Binary Tree","Binary Tree Properties","3-4 hrs","Balanced Binary Tree","https://leetcode.com/problems/balanced-binary-tree/","Easy"),
    (13,"Binary Tree","Binary Tree Properties","3-4 hrs","Same Tree","https://leetcode.com/problems/same-tree/","Easy"),
    (13,"Binary Tree","Binary Tree Properties","3-4 hrs","Invert Binary Tree","https://leetcode.com/problems/invert-binary-tree/","Easy"),
    (13,"Binary Tree","Binary Tree Properties","3-4 hrs","Path Sum","https://leetcode.com/problems/path-sum/","Easy"),
    (14,"Binary Tree","Binary Tree Advanced","~4 hrs","Binary Tree Maximum Path Sum","https://leetcode.com/problems/binary-tree-maximum-path-sum/","Hard"),
    (14,"Binary Tree","Binary Tree Advanced","~4 hrs","Construct BT from Preorder and Inorder","https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/","Medium"),
    (14,"Binary Tree","Binary Tree Advanced","~4 hrs","Serialize and Deserialize Binary Tree","https://leetcode.com/problems/serialize-and-deserialize-binary-tree/","Hard"),
    (14,"Binary Tree","Binary Tree Advanced","~4 hrs","Flatten Binary Tree to Linked List","https://leetcode.com/problems/flatten-binary-tree-to-linked-list/","Medium"),
    (14,"Binary Tree","Binary Tree Advanced","~4 hrs","LCA of Binary Tree","https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/","Medium"),
    (14,"Binary Tree","Binary Tree Advanced","~4 hrs","Vertical Order Traversal of BT","https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/","Hard"),
    (15,"BST","BST Basics","3-4 hrs","Validate Binary Search Tree","https://leetcode.com/problems/validate-binary-search-tree/","Medium"),
    (15,"BST","BST Basics","3-4 hrs","Search in a Binary Search Tree","https://leetcode.com/problems/search-in-a-binary-search-tree/","Easy"),
    (15,"BST","BST Basics","3-4 hrs","Insert into a Binary Search Tree","https://leetcode.com/problems/insert-into-a-binary-search-tree/","Medium"),
    (15,"BST","BST Basics","3-4 hrs","Delete Node in a BST","https://leetcode.com/problems/delete-node-in-a-bst/","Medium"),
    (15,"BST","BST Basics","3-4 hrs","Kth Smallest Element in a BST","https://leetcode.com/problems/kth-smallest-element-in-a-bst/","Medium"),
    (15,"BST","BST Basics","3-4 hrs","Lowest Common Ancestor of a BST","https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/","Medium"),
    (16,"BST","BST & Misc","~4 hrs","Recover Binary Search Tree","https://leetcode.com/problems/recover-binary-search-tree/","Medium"),
    (16,"BST","BST & Misc","~4 hrs","Convert Sorted Array to BST","https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/","Easy"),
    (16,"BST","BST & Misc","~4 hrs","Convert Sorted List to BST","https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/","Medium"),
    (16,"BST","BST & Misc","~4 hrs","Range Sum of BST","https://leetcode.com/problems/range-sum-of-bst/","Easy"),
    (16,"BST","BST & Misc","~4 hrs","Binary Search Tree Iterator","https://leetcode.com/problems/binary-search-tree-iterator/","Medium"),
    (16,"BST","BST & Misc","~4 hrs","Two Sum IV - Input is a BST","https://leetcode.com/problems/two-sum-iv-input-is-a-bst/","Easy"),
    (17,"Recursion","Recursion + Backtracking I","~4 hrs","Subsets","https://leetcode.com/problems/subsets/","Medium"),
    (17,"Recursion","Recursion + Backtracking I","~4 hrs","Subsets II","https://leetcode.com/problems/subsets-ii/","Medium"),
    (17,"Recursion","Recursion + Backtracking I","~4 hrs","Combination Sum","https://leetcode.com/problems/combination-sum/","Medium"),
    (17,"Recursion","Recursion + Backtracking I","~4 hrs","Combination Sum II","https://leetcode.com/problems/combination-sum-ii/","Medium"),
    (17,"Recursion","Recursion + Backtracking I","~4 hrs","Permutations","https://leetcode.com/problems/permutations/","Medium"),
    (17,"Recursion","Recursion + Backtracking I","~4 hrs","Permutations II","https://leetcode.com/problems/permutations-ii/","Medium"),
    (18,"Backtracking","Recursion + Backtracking II","4-5 hrs","N-Queens","https://leetcode.com/problems/n-queens/","Hard"),
    (18,"Backtracking","Recursion + Backtracking II","4-5 hrs","Sudoku Solver","https://leetcode.com/problems/sudoku-solver/","Hard"),
    (18,"Backtracking","Recursion + Backtracking II","4-5 hrs","Word Search (Backtracking)","https://leetcode.com/problems/word-search/","Medium"),
    (18,"Backtracking","Recursion + Backtracking II","4-5 hrs","Palindrome Partitioning","https://leetcode.com/problems/palindrome-partitioning/","Medium"),
    (18,"Backtracking","Recursion + Backtracking II","4-5 hrs","Generate Parentheses","https://leetcode.com/problems/generate-parentheses/","Medium"),
    (18,"Backtracking","Recursion + Backtracking II","4-5 hrs","Unique Paths III","https://leetcode.com/problems/unique-paths-iii/","Hard"),
    (19,"Bit Manipulation","Bit Manipulation","3-4 hrs","Single Number","https://leetcode.com/problems/single-number/","Easy"),
    (19,"Bit Manipulation","Bit Manipulation","3-4 hrs","Single Number II","https://leetcode.com/problems/single-number-ii/","Medium"),
    (19,"Bit Manipulation","Bit Manipulation","3-4 hrs","Counting Bits","https://leetcode.com/problems/counting-bits/","Easy"),
    (19,"Bit Manipulation","Bit Manipulation","3-4 hrs","Number of 1 Bits","https://leetcode.com/problems/number-of-1-bits/","Easy"),
    (19,"Bit Manipulation","Bit Manipulation","3-4 hrs","Reverse Bits","https://leetcode.com/problems/reverse-bits/","Easy"),
    (19,"Bit Manipulation","Bit Manipulation","3-4 hrs","Sum of Two Integers (Bitwise)","https://leetcode.com/problems/sum-of-two-integers/","Medium"),
    (20,"Dynamic Programming","1D DP Basics","3-4 hrs","Climbing Stairs","https://leetcode.com/problems/climbing-stairs/","Easy"),
    (20,"Dynamic Programming","1D DP Basics","3-4 hrs","House Robber","https://leetcode.com/problems/house-robber/","Medium"),
    (20,"Dynamic Programming","1D DP Basics","3-4 hrs","House Robber II","https://leetcode.com/problems/house-robber-ii/","Medium"),
    (20,"Dynamic Programming","1D DP Basics","3-4 hrs","Coin Change","https://leetcode.com/problems/coin-change/","Medium"),
    (20,"Dynamic Programming","1D DP Basics","3-4 hrs","Min Cost Climbing Stairs","https://leetcode.com/problems/min-cost-climbing-stairs/","Easy"),
    (20,"Dynamic Programming","1D DP Basics","3-4 hrs","Partition Equal Subset Sum","https://leetcode.com/problems/partition-equal-subset-sum/","Medium"),
    (21,"Dynamic Programming","1D / 2D DP","~4 hrs","Longest Increasing Subsequence","https://leetcode.com/problems/longest-increasing-subsequence/","Medium"),
    (21,"Dynamic Programming","1D / 2D DP","~4 hrs","Longest Common Subsequence","https://leetcode.com/problems/longest-common-subsequence/","Medium"),
    (21,"Dynamic Programming","1D / 2D DP","~4 hrs","Edit Distance","https://leetcode.com/problems/edit-distance/","Hard"),
    (21,"Dynamic Programming","1D / 2D DP","~4 hrs","Unique Paths","https://leetcode.com/problems/unique-paths/","Medium"),
    (21,"Dynamic Programming","1D / 2D DP","~4 hrs","Unique Paths II","https://leetcode.com/problems/unique-paths-ii/","Medium"),
    (21,"Dynamic Programming","1D / 2D DP","~4 hrs","Decode Ways","https://leetcode.com/problems/decode-ways/","Medium"),
    (22,"Dynamic Programming","DP on Strings","4-5 hrs","Longest Palindromic Substring","https://leetcode.com/problems/longest-palindromic-substring/","Medium"),
    (22,"Dynamic Programming","DP on Strings","4-5 hrs","Palindromic Substrings","https://leetcode.com/problems/palindromic-substrings/","Medium"),
    (22,"Dynamic Programming","DP on Strings","4-5 hrs","Word Break","https://leetcode.com/problems/word-break/","Medium"),
    (22,"Dynamic Programming","DP on Strings","4-5 hrs","Distinct Subsequences","https://leetcode.com/problems/distinct-subsequences/","Hard"),
    (22,"Dynamic Programming","DP on Strings","4-5 hrs","Interleaving String","https://leetcode.com/problems/interleaving-string/","Medium"),
    (22,"Dynamic Programming","DP on Strings","4-5 hrs","Regular Expression Matching","https://leetcode.com/problems/regular-expression-matching/","Hard"),
    (23,"Dynamic Programming","DP Misc / Optimization","4-5 hrs","Maximum Product Subarray","https://leetcode.com/problems/maximum-product-subarray/","Medium"),
    (23,"Dynamic Programming","DP Misc / Optimization","4-5 hrs","Best Time to Buy and Sell Stock II","https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/","Medium"),
    (23,"Dynamic Programming","DP Misc / Optimization","4-5 hrs","Best Time to Buy and Sell Stock III","https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/","Hard"),
    (23,"Dynamic Programming","DP Misc / Optimization","4-5 hrs","Jump Game","https://leetcode.com/problems/jump-game/","Medium"),
    (23,"Dynamic Programming","DP Misc / Optimization","4-5 hrs","Jump Game II","https://leetcode.com/problems/jump-game-ii/","Medium"),
    (23,"Dynamic Programming","DP Misc / Optimization","4-5 hrs","Minimum Path Sum","https://leetcode.com/problems/minimum-path-sum/","Medium"),
    (24,"Graphs","Graph Basics","3-4 hrs","Clone Graph","https://leetcode.com/problems/clone-graph/","Medium"),
    (24,"Graphs","Graph Basics","3-4 hrs","Number of Islands","https://leetcode.com/problems/number-of-islands/","Medium"),
    (24,"Graphs","Graph Basics","3-4 hrs","Find if Path Exists in Graph","https://leetcode.com/problems/find-if-path-exists-in-graph/","Easy"),
    (24,"Graphs","Graph Basics","3-4 hrs","Course Schedule","https://leetcode.com/problems/course-schedule/","Medium"),
    (24,"Graphs","Graph Basics","3-4 hrs","Course Schedule II","https://leetcode.com/problems/course-schedule-ii/","Medium"),
    (24,"Graphs","Graph Basics","3-4 hrs","Surrounded Regions","https://leetcode.com/problems/surrounded-regions/","Medium"),
    (25,"Graphs","Graph Advanced","4-5 hrs","Word Ladder","https://leetcode.com/problems/word-ladder/","Hard"),
    (25,"Graphs","Graph Advanced","4-5 hrs","Pacific Atlantic Water Flow","https://leetcode.com/problems/pacific-atlantic-water-flow/","Medium"),
    (25,"Graphs","Graph Advanced","4-5 hrs","Graph Valid Tree","https://leetcode.com/problems/graph-valid-tree/","Medium"),
    (25,"Graphs","Graph Advanced","4-5 hrs","Number of Connected Components","https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/","Medium"),
    (25,"Graphs","Graph Advanced","4-5 hrs","Shortest Path in Binary Matrix","https://leetcode.com/problems/shortest-path-in-binary-matrix/","Medium"),
    (25,"Graphs","Graph Advanced","4-5 hrs","Network Delay Time (Dijkstra)","https://leetcode.com/problems/network-delay-time/","Medium"),
    (26,"Greedy","Greedy","3-4 hrs","Non-overlapping Intervals","https://leetcode.com/problems/non-overlapping-intervals/","Medium"),
    (26,"Greedy","Greedy","3-4 hrs","Meeting Rooms II","https://leetcode.com/problems/meeting-rooms-ii/","Medium"),
    (26,"Greedy","Greedy","3-4 hrs","Gas Station","https://leetcode.com/problems/gas-station/","Medium"),
    (26,"Greedy","Greedy","3-4 hrs","Assign Cookies","https://leetcode.com/problems/assign-cookies/","Easy"),
    (26,"Greedy","Greedy","3-4 hrs","Minimum Number of Arrows to Burst Balloons","https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/","Medium"),
    (26,"Greedy","Greedy","3-4 hrs","Jump Game (Greedy approach)","https://leetcode.com/problems/jump-game/","Medium"),
    (27,"Mixed Hard","Remaining Hard Problems","4-5 hrs","N-Queens II","https://leetcode.com/problems/n-queens-ii/","Hard"),
    (27,"Mixed Hard","Remaining Hard Problems","4-5 hrs","Wildcard Matching","https://leetcode.com/problems/wildcard-matching/","Hard"),
    (27,"Mixed Hard","Remaining Hard Problems","4-5 hrs","Best Time to Buy and Sell Stock IV","https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/","Hard"),
    (27,"Mixed Hard","Remaining Hard Problems","4-5 hrs","Burst Balloons","https://leetcode.com/problems/burst-balloons/","Hard"),
    (27,"Mixed Hard","Remaining Hard Problems","4-5 hrs","Trapping Rain Water","https://leetcode.com/problems/trapping-rain-water/","Hard"),
    (27,"Mixed Hard","Remaining Hard Problems","4-5 hrs","Maximum XOR of Two Numbers in Array","https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/","Medium"),
    (28,"Revision","Re-solve Weak Topics","3-4 hrs","[Pick your weakest topic Q1]","",""),
    (28,"Revision","Re-solve Weak Topics","3-4 hrs","[Pick your weakest topic Q2]","",""),
    (28,"Revision","Re-solve Weak Topics","3-4 hrs","[Pick your weakest topic Q3]","",""),
    (28,"Revision","Re-solve Weak Topics","3-4 hrs","[Pick your weakest topic Q4]","",""),
    (28,"Revision","Re-solve Weak Topics","3-4 hrs","[Pick your weakest topic Q5]","",""),
    (28,"Revision","Re-solve Weak Topics","3-4 hrs","[Pick your weakest topic Q6]","",""),
    (29,"Mixed Mock","Mixed Mock Day","3-4 hrs","[Mock Q1 - Array/String]","",""),
    (29,"Mixed Mock","Mixed Mock Day","3-4 hrs","[Mock Q2 - Array/String]","",""),
    (29,"Mixed Mock","Mixed Mock Day","3-4 hrs","[Mock Q3 - Linked List]","",""),
    (29,"Mixed Mock","Mixed Mock Day","3-4 hrs","[Mock Q4 - Tree]","",""),
    (29,"Mixed Mock","Mixed Mock Day","3-4 hrs","[Mock Q5 - DP]","",""),
    (29,"Mixed Mock","Mixed Mock Day","3-4 hrs","[Mock Q6 - Graph or Heap]","",""),
    (30,"Full Review","Full Review + Notes","~4 hrs","Sliding Window pattern revision","",""),
    (30,"Full Review","Full Review + Notes","~4 hrs","Two Pointers pattern revision","",""),
    (30,"Full Review","Full Review + Notes","~4 hrs","Binary Search on Answer revision","",""),
    (30,"Full Review","Full Review + Notes","~4 hrs","DP patterns (Knapsack, LIS, LCS, grid)","",""),
    (30,"Full Review","Full Review + Notes","~4 hrs","Tree / Graph traversal templates","",""),
    (30,"Full Review","Full Review + Notes","~4 hrs","C++ snippet templates (fast I/O, DSU, Dijkstra)","",""),
]

if __name__ == '__main__':
    print('Run: python generate_timetable.py')
    print('Output: Striver_SDE_30Day_Timetable.xlsx')
